### ISSUE TITLE
select_room example should keep the room name in the input field

### ISSUE THREAD

**Issue by b3aribeiro** [jbakse/p5.party#52]
This feature request is related to the "[Is it possible to create multiple rooms through the use of entry keys?](https://github.com/jbakse/p5.party/discussions/48#discussioncomment-2093228)" discussion thread:

**What currently happens:**
The experimental example, [select_room](https://p5party.netlify.app/show_example.html?select_room), is currently refreshing the HTML input field back to "main" once the user clicks in the "Join Room" button. 

**What should happen:**
After typing the custom room name into the HTML input field and clicking "Join Room", the typed name should remain exposed in the input field, so the users can remember/share their key to friends.

**Comment by jbakse** [comment]
Yes, this would be a good addition.

**Comment by jbakse** [comment]
fixed in 5a54c0da07fe6db1eed9766ddf1f9f35314ae737
