### ISSUE TITLE
Add function to return active participant ids and roles in a room

### ISSUE THREAD

**Issue by huaigulin** [jbakse/p5.party#54]
Currently, p5.party displays active participant ids and their roles in the info panel.

We could use [partyLoadParticipantShareds()](https://www.notion.so/partyLoadParticipantShareds-2a88fb13a98f4f87b5d1e3d63d82c3c5) or implement a new function to return these information.

These information would make it easier to develop game experiences that depend on active
players. Game developers would know if a player joined or left a room, and update game status accordingly.

**Comment by jbakse** [comment]
Just confirming: by roles you mean "which participant is currently the host?". 

I agree that this is a feature that should likely be developed. It would help a lot to put out some proposals for how the feature's API should work and how it will be used.

Would you be up for replying here with a short proposal of what the API calls would be, what they should return, and maybe even a small sample code showing how it might be used?

**Comment by jbakse** [comment]
This is currently being discussed here: https://www.notion.so/Notes-from-Kevin-Lin-086c4e2bc487462dad7062137f8a4493
