### ISSUE TITLE
ToggleInfo Button not showing up

### ISSUE THREAD

**Issue by BlueSage96** [jbakse/p5.party#55]
**Describe the bug**
I added the code to create a toggle info button for my rocket game. It was working at first but I had to close p5 because I was having an issue with the editor. When I reopened my sketch the button no longer shows up even though I have the code in setup().

**p5.js and p5.party versions**
p5.js - not sure  
p5.party - 0.7.0

  if(partyIsHost()){
    partyToggleInfo(false);
    createButton("Toggle Info").mousePressed(()=> {
      partyToggleInfo();
    }); 
  }

**Screenshots**
![Image 2-13-22 at 3 06 PM](https://user-images.githubusercontent.com/47897744/153772761-aff84304-2555-4735-a1ab-8cc598eb777d.jpg)

As you can see the toggle info button is missing. It was there earlier.

**Comment by jbakse** [comment]
You are creating the toggle button only if the client is host on startup. The client in the screenshot is not the host, so no button is being made. Please confirm here if that is the issue, and I'll close this issue.

BTW: this is a good, clear issue report with all the info needed to respond. Thanks.

**Comment by BlueSage96** [comment]
Ok, I see. I had the game open in another tab. Once I closed that tab the toggle came back.
