### ISSUE TITLE
An asynchrony on reading shared object between sender client and receiver clients when using partyEmit().

### ISSUE THREAD

**Issue by ShaoT-Hugh** [jbakse/p5.party#59]
_I'm not sure if it's really a bug or it's just supposed to work like that, but I decide to post it here._

(Please review my code at the bottom)
In my test code, when a player click the mouse, it will add 1 to the shared object named `shared.count`, and send out a `"showChange"` event to other clients simultaneously using `partyEmit("showChange")`. `"showChange"` event will trigger a `showChange()` function in every client, and `showChange()` function will print the value of `shared.count` in the console.

**Expected behavior**
`showChange()` function is expected to print the **changed value** of  `shared.count`. That is to say, if the initial value of `shared.count` is 1, when I click the mouse, I'm supposed to have a 2 in the console.

An expected process would be:

1. initially, `shared.count` is 1;
2. I click the mouse;
3. `shared.count` changes from 1 to 2;
4. a `"showChange"` event is sent to the party;
5. every client receives `"showChange"` event;
6. every client has `shared.count`(should be 2 now) printed in their consoles.

**Observed behavior**
On the sender client(the client that sent `"showChange"` event), the above process happened expectedly. I got 2 in the console finally.

However, on the receiver client(other clients that received `"showChange"` event), **there was 1 in the console instead of 2** in step 6. That means the receiver client didn't read the changed value of `shared.count` but read the previous value.

If the receiver client read `shared.count` after the execution of `showChange()`, it can have the right changed value that is 2. So the asynchrony only happens for an instant after `partyEmit()`.

**p5.js and p5.party versions**
I think it's the latest version as the source is https://cdn.jsdelivr.net/npm/p5.party@latest/dist/p5.party.js 

**Error Message**
No, there isn't an error. The program can still run.

**Your code**
Here is my test code in p5 editor.
```javascript
var shared;

function preload() {
  partyConnect(
    "wss://deepstream-server-1.herokuapp.com",
    "async_example",
    "room_0"
  );
  
  shared = partyLoadShared("shared");
}

function setup() {
  createCanvas(300, 300);
  background(0);
  
  if(partyIsHost()) shared.count = 1; // initial value is 1
  
  partySubscribe("showChange", showChange);
}

function showChange() {
  console.log("init: " + shared.count); // sender gets the changed value, while receiver gets the previous value
  let countdown = setInterval(function() {
    console.log(shared.count);
  }, 10); // if trying to get shared.count an instant later, both sender and receiver can have the changed value 
  setTimeout(function() {
    clearInterval(countdown);
  }, 100);
}

// when clicking the mouse, add 1 to shared.count and tell party to run showChange() to see the changed number in console
function mouseClicked() {
  let x = mouseX, y = mouseY;
  if(x < width && y < height) {
// change of shared.count and sending of 'showChange' event happen together here
    shared.count ++;
    partyEmit("showChange");
    
// This is my current solution - delay the execution of partyEmit(), and it works expectedly; but it looks weird
    // setTimeout(function() {
    //   partyEmit("showChange");
    // }, 50);
  }
}
```

**Comment by jbakse** [comment]
This is a race condition. And its a pretty literal example of a race too!

You start the race when you change `shared.count` and emit a "showChange" event at just about the exact same time. Those messages are making a trip to the server and then to the other clients.

Sometimes the change to `shared.count` wins. In that case, when the "showChange" event arrives `shared.count` has the lastest value.

Sometimes "showChange" gets there first. And `shared.count` just hasn't been updated yet.

You _could_ wrap your partyEmit call in a set timeout.

```javascript
setTimeout(()=>{partyEmit("showChange");}, 100);
```
That would give a head start to the `shared.count` change, and you'd probably get what you want almost all the time. But no matter how much of a headstart you give `shared.count` its still a race. If `shared.count` is super slow for some strange reason, it might still lose.

I'm not sure what you were originally trying to do, but there is a pretty good chance that you want to use "partyWatchShared()" which will call your callback when a specific shared value changes.

https://www.notion.so/partyWatchShared-a86a067493da4e889e126dd5a2bf5d18

**Comment by ShaoT-Hugh** [comment]
Thanks. I see it. I also reread _Avoiding Data Conflicts_ doc and found
> "When one client sets a value on a shared object, the change is immediately updated on the local object. The value change is also sent to the server and then broadcast to all the other clients. It takes some time..."

Previously, I thought when reading from a shared object, all the client should get the same data(either the previous data or the latest data). But actually the writer can immediately get the lastest one because the writer reads from its local object? So this generates an asynchrony between the writer and the receivers?

Also for this specific question, I felt this could be a problem because it was kinda counter-intuitive --- I thought I had considered all the caveats we talked about shared object early, but as `partySubscribe()` and `partyEmit()` were introduced lately, some new issues showed up with them and I would doubt whether the problem is related to them or not. Even though we had been informed that p5.party couldn't guarantee the order of data exchange, it's still not easy to always keep it in mind and quickly realize that the cause is `race condition` in such a new specific condition.
The only thing I can grasp is to pay more attention to `race condition` next time I encounter similar questions. And hopefully, it would be better that my experience could remind others of this specific question in advance :-)
