### ISSUE TITLE
Ability to lock rooms after a number of players have entered

### ISSUE THREAD

**Issue by BlueSage96** [jbakse/p5.party#62]
I think having this ability would be useful when p5.party is stable and there are many more people using it. An alternative is having players become participants after a certain number of players but maybe just having so many people in one room could cause lag. Another alternative would be to make multiple rooms for people to join but again it would be good to limit the number of players in each room. This request comes from the lag from having so many people trying out game b at once.

**Comment by jbakse** [comment]
This is an interesting suggestion.

I think limiting the number of clients in a room (and especially designating some clients as "players" and others as "observers") is probably too high level: different projects will have different specific needs related to this.

However, I think that the toolbox provided might not provide all the tools needed for app developers to do this on their own. You can't check how many clients are in a room without connecting right now. There is also no way to leave the room without unloading the sketch. Both of these seem like important API features to consider.

You mention possible performance problems in this comment, but a typical scale (less than 10 clients in a room), I don't think the number of (reading only) clients is going to have a big impact on performance. If it does, it might be something about the approach in the app code, or it might be an issue with p5.party. If you have an example, we can look through it.

**Comment by BlueSage96** [comment]
Yeah I think have a way to manually leave a room would be great right now especially when testing games. There were several times when someone forgot to close the game and Malin and I had to keep changing the room. Maybe there could be some kind of function that removes people from a room if they are inactive after a certain amount of time. Kind of like the FAFSA website or the SHS portal.
