### ISSUE TITLE
Free Heroku plans are no more

### ISSUE THREAD

**Issue by rahji** [jbakse/p5.party#69]
FYI: Starting November 28th, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available.
If you have apps using any of these resources, you must upgrade to paid plans by this date to ensure your apps continue to run and to retain your data. For students, we will announce a new program by the end of September.  [Learn more](https://blog.heroku.com/next-chapter)

**Comment by jbakse** [comment]
Update docs to reflect this.
